apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uat
resources:
  - ../../_base
patches:
  - path: uat.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: basic-api
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "-timeout=8"
