name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, closed]
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  pipeline:
    uses: mpandouris/platform/.github/workflows/golang-pipeline.yaml@kustomize
    with:
      service_name: basic-api
      allow_feature_branch_deployment: true
    secrets: inherit