apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: basic-api
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 128m
              memory: 128Mi